### ISSUE TITLE
Extract breakdown year for a subset of the non-functional wells

### ISSUE THREAD

**Issue by chase-dwelle** [yeemey/haackwell#12]
There are ~1500 wells that have "Breakdown year:[YEAR]" in the `STATUS` message, e.g.,

WELL_ID | LAT_DD | LONG_DD | FUNC | STATUS | COD_FCN | COD_QTY | COD_RESRCE | ADM1 | ADM2 | ACTIVITY | COUNTRY | WATERSRC | WATERTECH | INSTALLED | MGMT | PAY | SOURCE | RPT_DATE
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
268998 | -10.71619084 | 36.02310299 | No | Status:Not functional\|Breakdown Year:1999\|Reason Not Functioning:Dam has   dried up\|Quantity:Dry\|Quality:Soft | 0 | 0 | 1 | Coast Region | Kisarawe |   | TZ | Dam | Gravity Communal standpipe | 1992 |   | Pay per bucket | Plan | 18/10/2009
282411 | -10.71532037 | 36.02752107 | No | Status:Not functional\|Breakdown   Year:2003\|Quantity:Insufficient\|Quality:Soft | 0 | 1 | 0 | Morogoro | Morogoro Rural | TZ | Dam | Gravity Communal standpipe | 2000 |   | Never pay | WA | 11/6/08
269003 | -10.71391058 | 35.9747595 | No | Status:Not functional\|Breakdown Year:2004\|Reason Not Functioning:Dam has   dried up\|Quantity:Dry\|Quality:Soft | 0 | 0 | 1 | Coast Region | Kisarawe |   | TZ | Dam | Gravity Dam | 1990 |   | Pay per bucket | Plan | 18/10/2009
269001 | -10.71294497 | 35.96916631 | No | Status:Not functional\|Breakdown Year:2004\|Reason Not Functioning:Dam has   dried up\|Quantity:Dry\|Quality:Soft | 0 | 0 | 1 | Coast Region | Kisarawe |   | TZ | Dam | Gravity Dam | 1970 |   | Pay per bucket | Plan | 18/10/2009
268081 | -10.71233895 | 36.031057 | No | Status:Not functional\|Breakdown Year:2005\|Reason Not Functioning:Also dam   broken\|Quantity:Dry\|Quality:Soft | 0 | 1 | 0 | Arusha | Monduli |   | TZ | Dam | Gravity Communal standpipe | 1993 |   | Never pay | WA | 15/06/2008
269067 | -10.71037391 | 35.9691566 | No | Status:Not functional\|Breakdown Year:2005\|Reason Not Functioning:Dam has   dried up\|Quantity:Dry\|Quality:Soft | 0 | 0 | 1 | Coast Region | Kisarawe |   | TZ | Dam | Gravity Communal standpipe | 1970 |   | Never pay | Plan | 18/10/2009
269070 | -10.71022388 | 35.97219087 | No | Status:Not functional\|Breakdown Year:2005\|Reason Not Functioning:Dam has   dried up\|Quantity:Dry\|Quality:Soft | 0 | 0 | 1 | Coast Region | Kisarawe |   | TZ | Dam | Gravity Communal standpipe | 1970 |   | Never pay | Plan | 18/10/2009
269014 | -10.7097919 | 36.03288676 | No | Status:Not functional\|Breakdown Year:2005\|Reason Not Functioning:Dam has   dried up\|Quantity:Dry\|Quality:Soft | 0 | 0 | 1 | Coast Region | Kisarawe |   | TZ | Dam | Gravity Hand pump | 1970 |   | Pay per bucket | Plan | 18/10/2009
269069 | -10.70841953 | 35.97085284 | No | Status:Not functional\|Breakdown Year:2005\|Reason Not Functioning:Dam has   dried up\|Quantity:Dry\|Quality:Soft | 0 | 0 | 1 | Coast Region | Kisarawe |   | TZ | Dam | Gravity Communal standpipe | 1970 |   | Never pay | Plan | 18/10/2009

This is useful information because it tells us the actual year where the well became nonfunctional, and we could use this date instead of the report date, which is often years later, for trying to pinpoint potential hydrologic causes.

Or, we could use the report date like we do with the rest of the data if we want to be consistent with the rest of the available data. Thoughts?

**Comment by yeemey** [comment]
In working on #7 , I'm subsetting the well data out to look at pump failure reasons, so I think this is useful info - am working on parsing out the 'STATUS' data into additional columns. I realize this isn't 'hydrological' or geospatial, but think it can be informative.
