### ISSUE TITLE
Remove gravity-fed wells from the well dataset

### ISSUE THREAD

**Issue by chase-dwelle** [yeemey/haackwell#2]
Right now, we have "wells" that are actually gravity fed, like a spring or a rainwater harvesting operation, e.g.,

WELL_ID | LAT_DD | LONG_DD | FUNC | STATUS | COD_FCN | COD_QTY | COD_RESRCE | ADM1 | ADM2 | ACTIVITY | COUNTRY | WATERSRC | WATERTECH | INSTALLED | MGMT | PAY | SOURCE | RPT_DATE
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
486554 | -0.12982 | 34.456458 | Yes | Functional ( in use) | 1 | 1 | 0 |   |   | ksm372 | KE | Rainwater (harvesting) | Gravity | 2005 | Institutional Management | None | Virtual Kenya | 6/6/12
485707 | -0.109488 | 34.438404 | Yes | Functional ( in use) | 1 | 1 | 0 |   |   | ksm367 | KE | Rainwater (harvesting) | Gravity | 2005 | Institutional Management | None | Virtual Kenya | 5/6/12
486748 | -0.123888 | 34.548462 | Yes | Functional ( in use) | 1 | 1 | 0 |   |   | ksm296 | KE | Rainwater (harvesting) | Gravity | 2008 | Institutional Management | 2 KES/20L Jerrican | Virtual Kenya | 25/04/2012
486747 | -0.123888 | 34.548462 | Yes | Functional ( in use) | 1 | 1 | 0 |   |   | ksm296 | KE | Rainwater (harvesting) | Gravity | 2008 | Institutional Management | 2 KES/20L Jerrican | Virtual Kenya | 25/04/2012

These have no relation to GRACE data (since GRACE is groundwater), and therefore should be removed.

**Comment by ehaacker** [comment]
We can probably keep the springs. We can think of springs as simply places where the groundwater level intersects with the land surface (so a well with a very small effective depth); they're going to be more vulnerable to depleted groundwater, so may be the first to respond to depletion recorded by GRACE. But rainwater harvesting won't be related to changes in groundwater storage - we could maybe still compare with precip, but shouldn't treat those the same as wells/springs.

**Comment by chase-dwelle** [comment]
Yep @ehaacker is right. I took the lat/lons of a few of the springs/lake sources and looked at them on Google Maps and it definitely seems like the SOURCE column is the source of the well, and not the type of water source. 

We then just need to delete the `Rainwater (harvesting)` entries.
